language: rust

matrix:
  include:
    rust:
    - stable
    - beta
    - nightly
      env: FLAGS="--features=nightly"

script:
  - cargo build --verbose $FLAGS
  - cargo test --verbose $FLAGS

env:
  global:
    - RUST_BACKTRACE=1

notifications:
  email:
    on_success: never
