language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env: FLAGS="--features=nightly"

script:
  - cargo build --verbose $FLAGS
  - cargo test --verbose $FLAGS

env:
  global:
    - RUST_BACKTRACE=1

notifications:
  email:
    on_success: never
